import express from 'express';
import { login, me, register, removeFcmToken, saveFcmToken } from '../controllers/authController.js';
import { protect } from '../middleware/auth.js';
const r = express.Router();
r.post('/register', register);
r.post('/login', login);
r.get('/me', protect, me);
r.post('/fcm-token', protect, saveFcmToken);
r.delete('/fcm-token', protect, removeFcmToken);
export default r;
